from service import inicializar_datos_ejemplo, validar_fechas, verificar_disponibilidad
from db import guardar_datos
from config import ARCHIVO_VEHICULOS, ARCHIVO_RESERVAS, ESTADO_DISPONIBLE, ESTADO_ALQUILADO, ESTADO_MANTENIMIENTO